version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./grafana/prometheus/targets.json:/etc/prometheus/targets.json
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    build: grafana
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=sbk
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  sbk:
    image: kmgowda/sbk
    container_name: sbk
    hostname: sbk
    depends_on:
      - prometheus
      - grafana
    expose:
      - 9718
    ports:
      - "9718:9718"
