version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    build: grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=sbk
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  sbk:
    build: .
    container_name: sbk
    hostname: sbk
    depends_on:
      - prometheus
      - grafana
    expose:
      - 8080
    ports:
      - "8080:8080"
