version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./../grafana/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    build: ./../grafana
    container_name: grafana
    hostname: grafana
    volumes:
      - ./../grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=sbk
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  sbk-ram:
    build:
      context: ./..
      dockerfile: ./dockers/sbk-ram
    container_name: sbk-ram
    hostname: sbk-ram
    depends_on:
      - prometheus
      - grafana
    ports:
      - '9716:9716'
      - '9719:9719'